### ISSUE TITLE
request: eliminate Bower

### ISSUE THREAD

**Issue by ctcpip** [rynam0/ember-swagger-ui#42]
Is there any way we can eliminate the bower dependency?  It is obsolete and Ember no longer uses it.

**Comment by rynam0** [comment]
It could be a while before I'll have a chance to take a look at this request. However, PRs are welcome and I agree the add-on should go the way of Ember and drop bower if possible. Thanks for raising the issue.

**Comment by rynam0** [comment]
I've begun to look into this @ctcpip, and have managed to at least integrate the newer swagger-ui-3.3.1 NPM package into the addon.  I have a bunch of work to do around this as swagger-ui was re-written from the ground up but it at least appears to be possible at this point.  More to follow.

**Comment by rynam0** [comment]
Addressed by #44
