### ISSUE TITLE
fresh install of ember-swagger-ui does not fetch petstore swagger spec

### ISSUE THREAD

**Issue by AKHarris** [rynam0/ember-swagger-ui#8]
I'm getting `Uncaught TypeError: Cannot read property 'type' of undefined` on a fresh install of the ember-swagger-ui addon. The top of the console error log points to bower_components/swagger-ui/dist/swagger-ui.js:253.

Here are the steps I took.

````bash
ember new ember-swag
cd ember-swag
# update bower.json file
# ember to 2.2.0
# ember-data to 2.2.0
# jquery to 2.1.x
bower install # update dependencies
ember install ember-swagger-ui
npm install
# update security policy in config/environment
ember s
# navigate to localhost:4200
````

![screen shot 2016-01-11 at 12 02 33 pm](https://cloud.githubusercontent.com/assets/5504772/12240401/3866393c-b85b-11e5-831f-69f32b720025.png)

Security Policy
````javascript
    contentSecurityPolicy: {
      'default-src': "'none'",
      'script-src': "'self' 'unsafe-inline' 'unsafe-eval' use.typekit.net",
      'font-src': "'self' data: use.typekit.net",
      'connect-src': "'self' *",
      'img-src': "'self' www.facebook.com p.typekit.net",
      'style-src': "'self' 'unsafe-inline' use.typekit.net"
    }
````

**Comment by AKHarris** [comment]
turns out that the variable `param` that's passed into a handlebars function is a function instead of an object.

![screen shot 2016-01-11 at 12 18 17 pm](https://cloud.githubusercontent.com/assets/5504772/12240779/62cce052-b85d-11e5-8a39-4bb0ddfa09c6.png)

**Comment by rynam0** [comment]
@AKHarris: Thanks for reporting!  Please try installing ember-swagger-ui@0.0.17.
The integration with swagger-ui-2.1.4 introduced in ember-swagger-ui@0.0.18 has not been tested fully. Looks like I'll have to reopen #7 for 2.1.4 support.  Thanks, again.

**Comment by AKHarris** [comment]
@rynam0 ember-swagger-ui version 0.0.17 works as expected :+1:

**Comment by rynam0** [comment]
Excellent.  Thanks for confirming :)

**Comment by rynam0** [comment]
FWIW: You ought to be able to use latest (0.0.19) now as I have reverted the changes for supporting 2.1.4.  I'll revisit 2.1.4 support and when I do, I'll be sure to vet it out more completely.  Thanks again.

**Comment by AKHarris** [comment]
@rynam0 awesome! I'll keep you posted. I'm poking at Ember with a stick at the moment (ditto with JavaScript in general tbh) and this addon looks like it could come in handy.
