### ISSUE TITLE
Re-initialize swagger UI based on binding to controller property

### ISSUE THREAD

**Issue by AKHarris** [rynam0/ember-swagger-ui#9]
Is there a way to re-render the swagger-ui component based on changing the swagger.json url or in-memory swagger JSON object? I'm trying to make a single swagger-ui page that can point to different swagger JSON specifications.

Is there a way to re-call `_initSwaggerUi` when the controller's url or JSON swagger object changes? At least I think that's what I'm asking. Here's an example of something I'm interested in.

````javascript
// app/controllers/some-swagger-controller
export default Ember.Controller.extend({
  // value that will be passed to the swagger-ui component
  swaggerUrl: 'https://petstore.swagger.io/v2/swagger.json', 

  actions: {
    updateUrl(newUrl) {
      this.set('swaggerUrl', newUrl);
    }
  }
})
````

````hbs
<!-- 
menu for toggling different version of an API
-->
<ul>
  <button {{action 'updateUrl' 'https://petstore.swagger.io/swagger.json' }}>V1 API</button>
  <button {{action 'updateUrl' 'https://petstore.swagger.io/v2/swagger.json' }}>V2 API</button>
</ul>

<!--
when swaggerUrl changes on some-swagger-controller could the swagger-ui re-render?
-->
{{swagger-ui url=swaggerUrl}}
````

**Comment by rynam0** [comment]
@AKHarris, I gave your use-case a quick try and I think you might be able to get by with the following:
```
  actions: {
    updateUrl(newUrl) {
      this.set('swaggerUrl', newUrl);
      window.swaggerUi.options.url = newUrl;
      window.swaggerUi.load();
    }
  }
```

**Comment by AKHarris** [comment]
@rynam0 that worked pretty well. I guess short of re-writing the entire SwaggerUI class as an Ember Object you just have to manually re-load swaggerUi off of the window. Thanks again for this addon, it's been helpful.

**Comment by rynam0** [comment]
Glad that got you by. Dealing with swaggerUi being bound to the window namespace has been on my list of things to do since I started in on the project. I'm hoping to have the time to invest in this in the near future.
